# Generated by Django 5.2.8 on 2025-11-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.CharField(default='League of Legends', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Nom complet')),
                ('club_role', models.CharField(choices=[('player', 'Joueur'), ('coach', 'Coach'), ('referee', 'Arbitre')], default='player', max_length=20)),
                ('game_role', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], default='top', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='esports.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tournament', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('A', 'Victoire Team A'), ('B', 'Victoire Team B'), ('D', 'Match nul'), ('P', 'Pas encore joué')], default='P', max_length=1)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='esports.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='esports.team')),
            ],
        ),
    ]
