# Generated by Django 5.2.8 on 2026-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, default='En ligne', max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='replay_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#36d4ff', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
