# Generated by Django 5.2.8 on 2026-04-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0002_match_live_url_match_location_match_replay_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('participants', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, default='En ligne', max_length=120)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
