# Generated by Django 5.2.8 on 2026-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='replay_url',
            field=models.URLField(blank=True, verbose_name='URL de la rediffusion'),
        ),
    ]
